### ISSUE TITLE
Set global prefix for all Controllers

### ISSUE THREAD

**Issue by VikashKothary** [reciplease/reciplease#48]
You've been setting `api/` in the controllers. See https://github.com/reciplease/reciplease/blob/934080e170728dba4b80a080bd212b3308e187c7/web/src/main/java/org/reciplease/controller/IngredientController.java#L21.

Personally I would set the `api/` prefix globally so that the controllers so that the controllers only deal with their resources. I feel like we'd have a pain scaling the current approach. 

A quick Google lead me to this: https://stackoverflow.com/questions/28006501/how-to-specify-prefix-for-all-controllers-in-spring-boot

I would also argue we should set the prefix to `api/v1`. I remember we talked about versioning by I don't remember what we said was the best practice so feel free to remind me. 😇 But my stance is we should version in the app server then remap the url using a web server from `reciplease.org/api/v1` to `api.reciplease.org/ingredients` and `api.reciplease.orrg/v1/ingredients`. This would give the best of both worlds.

**Comment by rhys-saldanha** [comment]
@VikashKothary The problem with setting a global prefix is it starts to apply to things I don't think it should

/api/actuator/health?
/api/swagger?

Technically they make sense, but if everything is prefixed, then /api means nothing

Regarding the /v1, that should be applied per controller too, so that we can have both v1 and in the future v2 controllers living in harmony.

**Comment by VikashKothary** [comment]
Hmm, makes sense. A few questions:

1) Do you think we should add `v1` to the current endpoints?
2) Should we add tests that all the endpoints follow the correct endpoint naming convention?
3) Then why do you add the `api` prefix to all endpoints? I agree with you but just want to understand your reasoning.
4) Is the plan to add a reverse proxy that blocks all endpoints without the prefix `/api`?

**Comment by rhys-saldanha** [comment]
@VikashKothary v1 probably isn't needed, we control the API and the UI, we should be able to refactor endpoints with a bit of big brain thinking.

/api probably isn't needed if it's under the api subdomain... 

Tests test everything already! I think

**Comment by VikashKothary** [comment]
So adding a prefix is useful in some cases when you're hosting the api behind a reverse proxy. But since we're not. Let's close this for now.
