### ISSUE TITLE
Create `main` / `develop` branches

### ISSUE THREAD

**Issue by VikashKothary** [reciplease/reciplease#49]
My 2 cents, we've got too many releases. 

I would suggest having a `develop` branch. When you want to create a merge request to the `main` branch which will release and deploy the project.

However this allows even smaller PRs and features. And you can release when you want. It also allows users decide between a stable version of the software i.e. `main` or the latest version of the software i.e. `develop`

**Comment by rhys-saldanha** [comment]
@VikashKothary With this project, I'm attempting the 'testing in prod' strategy. Given that everything should always be deployed, there's then no need for a develop branch. I am happy to migrate to main - got a fancy git command that'll create a main and remove master?

All changes should be self-contained an non breaking. If something is a work in progress, consider adding a feature flag and only enabling it for some people (like you and I).

**Comment by VikashKothary** [comment]
I don't think this is an issue for now, so I'm happy to close this issue. But it may need to discussed again in the future.

I'm a huge fan of the `testing in prod` strategy. But then I think we then need to implement a phased adoption so only x number of users try the latest commits. My opinion is that you can't trust a change is self-contained and non-breaking until it's deployed and used by users. I believe most users are not as accepting of bugs and my opinion is that without the phased adoption, we'll see a lot of unhappy users.

My idea was also that we could create psudo-environments for DEV, QA and STAGE using proportions of the prod traffic. Then could allow users to opt-in to the each environment so most users still get a stable experience. 

P.S. what do you use for feature flags and how do you implement a phased `testing in prod` strategy?

**Comment by rhys-saldanha** [comment]
@VikashKothary I'll show an example in good time, especially on how to control features in the UI with a /user/features call 😏
